### ISSUE TITLE
Use distance threshold when suppressing click.

### ISSUE THREAD

**Issue by ocombe** [d3/d3-zoom#65]
Hello, there's a really old bug in chrome on Windows where it triggers the mousemove event on a simple click (even if the mouse is not moving).
See these: https://code.google.com/p/chromium/issues/detail?id=161464 & https://bugs.chromium.org/p/chromium/issues/detail?id=327114

The problem here is that the "zoom" event of d3 is triggered when this happens which prevents the real click event to go though.
I've worked around my problem with:

``` ts
d3.select(this.plotChart)
            .on('mousemove', () => {
                if(this.mousePos) {
                    let event = d3.event;
                    // because of a bug in chromium https://code.google.com/p/chromium/issues/detail?id=161464
                    if(event.x === this.mousePos.x && event.y === this.mousePos.y) {
                        event.stopPropagation();
                        event.preventDefault();
                        this.mousePos = undefined;
                    }
                }
            })
            .on('mousedown touchstart', () => {
                let event = d3.event;
                this.mousePos = {
                    x: event.x,
                    y: event.y
                };
            })
            .on('mouseup touchend', () => {
                this.mousePos = undefined;
            })

// ...
zoomHandler() {
  let event = d3.event;
  // ignore events when the mouse is not moving because of a bug in chromium https://code.google.com/p/chromium/issues/detail?id=161464
  if(event.sourceEvent.x === this.mousePos.x && event.sourceEvent.y === this.mousePos.y) {
    return;
  }
  // ...
}
```

But it would be better if you could take this into account in your lib.

I know that it's not your lib's fault, it's chrome's, but this bug has been opened since so long that I don't expect to see it fixed any time soon...

**Comment by mbostock** [comment]
This is equivalent to d3/d3-drag#28 but for d3-zoom.

**Comment by ocombe** [comment]
Probably yes

**Comment by mbostock** [comment]
Fixed in #97.

**Comment by wal0x** [comment]
Seriously, this bug is still bothering chromium users! Why they can't fix it!

**Comment by mbostock** [comment]
@wal0x Are you using d3-zoom 1.2.0? This release has not yet been merged into the [d3 default bundle](https://github.com/d3/d3), which is currently at 4.8.0. If you are using d3-zoom 1.2, please read my instructions on [reporting an issue](https://gist.github.com/mbostock/370b737ce71bed0749e103b01ce1bfaf).

**Comment by ocombe** [comment]
@mbostock I think he was just unhappy about the chrome developers, not you :)

**Comment by wal0x** [comment]
@ocombe @mbostock haha yes I was just mad at the chrome guys in the wrong place sorry mate :p

**Comment by mbostock** [comment]
Thanks for the clarification. Regardless of who you are mad at, please try to channel that energy into productive comments. Thank you!

**Comment by wal0x** [comment]
@mbostock to keep this feed clean, I ll delete my comments in 3.2.1... sorry for spamming again, cheers!
